# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - M324Todo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://m324containerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_40e6b3f4842a495f8fbc2eb1318c1b9f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2ce00b50576f465db4301dc19bf30b55 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: m324containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40e6b3f4842a495f8fbc2eb1318c1b9f }}/todo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'M324Todo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e6a53d0b402f4633b29f0731bf45fcdc }}
        images: 'm324containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_40e6b3f4842a495f8fbc2eb1318c1b9f }}/todo:${{ github.sha }}'